name: Deploy Test

on:
  push:
    branches:
      - github-ci
      - main 

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ShiroForbes-2
            git pull
            pkill -f Shiroforbes2ApplicationKt || true
            screen -dmS shiroforbes ./robust_restarter.sh
