name: CI Tests and Checks

on:
  push:
    branches:
      - '**'

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy a Google Service Account Key
        run: echo "${{ secrets.GOOGLE_API_KEY_BASE_64 }}" | base64 --decode > ./src/main/resources/service-account-key.json

      - name: Run Tests
        run: ./gradlew test

      - name: Store Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

  check-formatting:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Linter
        run: ./gradlew spotlessCheck

  static-analysis:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Static Analyzer
        run: ./gradlew detekt